import csv
import io
from flask import Blueprint, Response, render_template, jsonify, request
from flask_jwt_extended import jwt_required, current_user
from App.controllers import (
    get_assets_by_status,
    get_discrepant_assets,
    get_all_rooms,
    get_room
)
from datetime import datetime

discrepancy_views = Blueprint('discrepancy_views', __name__, template_folder='../templates')

@discrepancy_views.route('/discrepancy-report', methods=['GET'])
@jwt_required()
def discrepancy_report_page():
    return render_template('discrepancy.html')

def get_discrepancies_as_json(discrepancies):
    """Helper function to format discrepancies with room names."""
    for asset in discrepancies:
        if asset.get('room_id'):
            room = get_room(asset['room_id'])
            asset['room_name'] = room.room_name if room else f"Room {asset['room_id']}"
        else:
            asset['room_name'] = "Unknown"

        if asset.get('last_located') and asset['last_located'] != asset['room_id']:
            last_room = get_room(asset['last_located'])
            asset['last_located_name'] = last_room.room_name if last_room else f"Room {asset['last_located']}"
    return jsonify(discrepancies)

def get_discrepancies_as_csv(discrepancies, filter_type):
    """Helper function to generate a CSV response for discrepancies."""
    output = io.StringIO()
    writer = csv.writer(output)
    
    writer.writerow(['Discrepancy Report'])
    writer.writerow(['Generated By', current_user.username])
    writer.writerow(['Date & Time', datetime.now().strftime('%Y-%m-%d %H:%M:%S')])
    writer.writerow(['Filter', filter_type.capitalize()])
    writer.writerow([])
    
    header = ['Asset ID', 'Description', 'Status', 'Assigned Room', 'Last Located', 'Brand', 'Model', 'Serial Number', 'Last Update']
    writer.writerow(header)
    
    for asset in discrepancies:
        writer.writerow([
            asset.get('id', ''), asset.get('description', ''), asset.get('status', ''),
            asset.get('room_name', 'Unknown'), asset.get('last_located_name', asset.get('room_name', 'Unknown')),
            asset.get('brand', ''), asset.get('model', ''), asset.get('serial_number', ''), asset.get('last_update', '')
        ])
    
    output.seek(0)
    timestamp = datetime.now().strftime('%Y%m%d_%H%M%S')
    filename = f"discrepancy_report_{timestamp}.csv"
    
    return Response(
        output.getvalue(),
        mimetype='text/csv',
        headers={'Content-Disposition': f'attachment; filename="{filename}"'}
    )


@discrepancy_views.route('/api/discrepancies', methods=['GET'])
@jwt_required()
def get_discrepancies_api():
    """
    API endpoint to get discrepancy assets.
    Supports filtering by status (e.g., ?status=Missing)
    and content negotiation for CSV download (Accept: text/csv).
    """
    status_filter = request.args.get('status')
    
    if status_filter in ["Missing", "Misplaced"]:
        discrepancies = get_assets_by_status(status_filter)
    else:
        status_filter = 'all' # for CSV filename
        discrepancies = get_discrepant_assets()

    # Content Negotiation: Check if the client wants CSV or JSON
    best_match = request.accept_mimetypes.best_match(['application/json', 'text/csv'])
    
    if best_match == 'text/csv':
        return get_discrepancies_as_csv(discrepancies, status_filter)
    else: # Default to JSON
        return get_discrepancies_as_json(discrepancies)


@discrepancy_views.route('/api/rooms', methods=['GET'])
@jwt_required()
def get_all_rooms_json():
    """API endpoint to get all rooms for relocation"""
    rooms = get_all_rooms()
    if not rooms:
        return jsonify([])
    rooms_json = [room.get_json() for room in rooms]
    return jsonify(rooms_json)